version: "3"

services:
  web:
    image: misskey:cisskey-v12.39.1
    build: .
    restart: always
    links:
      - db
      - redis
#      - es
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - internal_network
      - nginx-proxy-bridge
    env_file:
      - .config/docker_web.env
    volumes:
      - /mnt/linux/cisskey_files:/misskey/files

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:12.2-alpine
    networks:
      - internal_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    networks:
#      - internal_network
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data

networks:
  internal_network:
    internal: true
  nginx-proxy-bridge:
    external: true
